version: "2"
linters:
  enable:
    - gosec
    - revive
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gosec:
      excludes:
        - G104
    revive:
      rules:
        - name: unexported-return
        - name: unused-parameter
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
