package output

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/Mutasem-mk4/procscope/internal/events"
	"github.com/Mutasem-mk4/procscope/internal/version"
)

// SummaryWriter generates a Markdown executive summary of an investigation.
type SummaryWriter struct {
	correlator  *events.Correlator
	allEvents   []*events.Event
	commandLine string
	targetPID   uint32
	startTime   time.Time
	endTime     time.Time
}

// NewSummaryWriter creates a SummaryWriter.
func NewSummaryWriter(
	correlator *events.Correlator,
	allEvents []*events.Event,
	commandLine string,
	targetPID uint32,
	startTime, endTime time.Time,
) *SummaryWriter {
	return &SummaryWriter{
		correlator:  correlator,
		allEvents:   allEvents,
		commandLine: commandLine,
		targetPID:   targetPID,
		startTime:   startTime,
		endTime:     endTime,
	}
}

// String renders the full Markdown summary.
func (s *SummaryWriter) String() string {
	var sb strings.Builder

	s.writeHeader(&sb)
	s.writeOverview(&sb)
	s.writeProcessTree(&sb)
	s.writeEventBreakdown(&sb)
	s.writeFileActivity(&sb)
	s.writeNetworkActivity(&sb)
	s.writeNotableEvents(&sb)
	s.writeLimitations(&sb)
	s.writeFooter(&sb)

	return sb.String()
}

// WriteToFile writes the summary to a file.
func (s *SummaryWriter) WriteToFile(path string) error {
	return os.WriteFile(path, []byte(s.String()), 0640)
}

func (s *SummaryWriter) writeHeader(sb *strings.Builder) {
	_, _ = sb.WriteString("# procscope Investigation Report\n\n")
	_, _ = sb.WriteString(fmt.Sprintf("**Investigation ID:** `%s`  \n", s.correlator.InvestigationID()))
	_, _ = sb.WriteString(fmt.Sprintf("**Generated by:** %s  \n", version.Full()))
	_, _ = sb.WriteString(fmt.Sprintf("**Date:** %s  \n\n", s.endTime.Format(time.RFC3339)))
}

func (s *SummaryWriter) writeOverview(sb *strings.Builder) {
	_, _ = sb.WriteString("## Overview\n\n")

	duration := s.endTime.Sub(s.startTime)

	_, _ = sb.WriteString("| Field | Value |\n")
	_, _ = sb.WriteString("|-------|-------|\n")
	if s.commandLine != "" {
		_, _ = sb.WriteString(fmt.Sprintf("| Command | `%s` |\n", s.commandLine))
	}
	_, _ = sb.WriteString(fmt.Sprintf("| Target PID | %d |\n", s.targetPID))
	_, _ = sb.WriteString(fmt.Sprintf("| Start Time | %s |\n", s.startTime.Format(time.RFC3339)))
	_, _ = sb.WriteString(fmt.Sprintf("| End Time | %s |\n", s.endTime.Format(time.RFC3339)))
	_, _ = sb.WriteString(fmt.Sprintf("| Duration | %s |\n", duration.Round(time.Millisecond)))
	_, _ = sb.WriteString(fmt.Sprintf("| Total Events | %d |\n", len(s.allEvents)))
	_, _ = sb.WriteString(fmt.Sprintf("| Processes Observed | %d |\n", len(s.correlator.ProcessTree())))
	_, _ = sb.WriteString("\n")
}

func (s *SummaryWriter) writeProcessTree(sb *strings.Builder) {
	_, _ = sb.WriteString("## Process Tree\n\n")
	_, _ = sb.WriteString("```\n")

	procs := s.correlator.ProcessTree()
	sort.Slice(procs, func(i, j int) bool {
		return procs[i].PID < procs[j].PID
	})

	for _, p := range procs {
		indent := strings.Repeat("  ", p.Depth)
		status := "running"
		if p.Exited {
			status = fmt.Sprintf("exit=%d", p.ExitCode)
		}
		_, _ = sb.WriteString(fmt.Sprintf("%s[%d] %s (%s)\n", indent, p.PID, p.Comm, status))
	}

	_, _ = sb.WriteString("```\n\n")
}

func (s *SummaryWriter) writeEventBreakdown(sb *strings.Builder) {
	_, _ = sb.WriteString("## Event Breakdown\n\n")

	stats := s.correlator.Stats()
	if len(stats) == 0 {
		_, _ = sb.WriteString("No events captured.\n\n")
		return
	}

	// Sort by count descending
	type kv struct {
		key   events.EventType
		count uint64
	}
	var pairs []kv
	for k, v := range stats {
		pairs = append(pairs, kv{k, v})
	}
	sort.Slice(pairs, func(i, j int) bool {
		return pairs[i].count > pairs[j].count
	})

	_, _ = sb.WriteString("| Event Type | Count | Confidence |\n")
	_, _ = sb.WriteString("|------------|-------|------------|\n")
	for _, p := range pairs {
		confidence := "best-effort"
		switch p.key {
		case events.EventExec, events.EventFork, events.EventExit,
			events.EventPrivSetUID, events.EventPrivSetGID:
			confidence = "exact"
		}
		_, _ = sb.WriteString(fmt.Sprintf("| `%s` | %d | %s |\n", p.key, p.count, confidence))
	}
	_, _ = sb.WriteString("\n")
}

func (s *SummaryWriter) writeFileActivity(sb *strings.Builder) {
	_, _ = sb.WriteString("## File Activity\n\n")

	// Collect unique files with operations
	type fileInfo struct {
		path string
		ops  map[string]bool
	}
	fileMap := make(map[string]*fileInfo)

	for _, evt := range s.allEvents {
		if evt.File == nil {
			continue
		}
		key := evt.File.Path
		if _, ok := fileMap[key]; !ok {
			fileMap[key] = &fileInfo{path: key, ops: make(map[string]bool)}
		}
		fileMap[key].ops[string(evt.Type)] = true
	}

	if len(fileMap) == 0 {
		_, _ = sb.WriteString("No file activity observed.\n\n")
		return
	}

	// Sort by path
	paths := make([]string, 0, len(fileMap))
	for p := range fileMap {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	// Limit to first 50 for readability
	max := 50
	if len(paths) > max {
		_, _ = sb.WriteString(fmt.Sprintf("> Showing first %d of %d files.\n\n", max, len(paths)))
		paths = paths[:max]
	}

	_, _ = sb.WriteString("| Path | Operations |\n")
	_, _ = sb.WriteString("|------|------------|\n")
	for _, p := range paths {
		fi := fileMap[p]
		ops := make([]string, 0, len(fi.ops))
		for op := range fi.ops {
			ops = append(ops, op)
		}
		sort.Strings(ops)
		_, _ = sb.WriteString(fmt.Sprintf("| `%s` | %s |\n", truncate(p, 80), strings.Join(ops, ", ")))
	}
	_, _ = sb.WriteString("\n")
}

func (s *SummaryWriter) writeNetworkActivity(sb *strings.Builder) {
	_, _ = sb.WriteString("## Network Activity\n\n")

	var netEvents []*events.Event
	for _, evt := range s.allEvents {
		if evt.Network != nil {
			netEvents = append(netEvents, evt)
		}
	}

	if len(netEvents) == 0 {
		_, _ = sb.WriteString("No network activity observed.\n\n")
		return
	}

	_, _ = sb.WriteString("| Type | PID | Comm | Family | Address | Port |\n")
	_, _ = sb.WriteString("|------|-----|------|--------|---------|------|\n")

	max := 50
	if len(netEvents) > max {
		_, _ = sb.WriteString(fmt.Sprintf("> Showing first %d of %d events.\n\n", max, len(netEvents)))
		netEvents = netEvents[:max]
	}

	for _, evt := range netEvents {
		n := evt.Network
		addr := n.DstAddr
		port := n.DstPort
		if addr == "" {
			addr = n.SrcAddr
			port = n.SrcPort
		}
		_, _ = sb.WriteString(fmt.Sprintf("| `%s` | %d | %s | %s | %s | %d |\n",
			evt.Type, evt.PID, evt.Comm, n.Family, addr, port))
	}
	_, _ = sb.WriteString("\n")
}

func (s *SummaryWriter) writeNotableEvents(sb *strings.Builder) {
	_, _ = sb.WriteString("## Notable Events\n\n")
	_, _ = sb.WriteString("> Notable events include privilege transitions, namespace changes, and mount operations.\n\n")

	var notable []*events.Event
	for _, evt := range s.allEvents {
		if evt.Type.IsNotable() {
			notable = append(notable, evt)
		}
	}

	if len(notable) == 0 {
		_, _ = sb.WriteString("No notable security-relevant events observed.\n\n")
		return
	}

	_, _ = sb.WriteString("| Time | PID | Event | Details |\n")
	_, _ = sb.WriteString("|------|-----|-------|---------|\n")

	tl := NewTimeline(false)
	for _, evt := range notable {
		elapsed := evt.Timestamp.Sub(s.startTime)
		detail := tl.eventDetail(evt)
		_, _ = sb.WriteString(fmt.Sprintf("| +%s | %d | `%s` | %s |\n",
			formatDuration(elapsed), evt.PID, evt.Type, detail))
	}
	_, _ = sb.WriteString("\n")
}

func (s *SummaryWriter) writeLimitations(sb *strings.Builder) {
	_, _ = sb.WriteString("## Limitations & Caveats\n\n")
	_, _ = sb.WriteString("This report was generated by procscope, a process-scoped runtime investigator.\n\n")
	_, _ = sb.WriteString("- **File activity** is best-effort: not all I/O paths are traced (e.g., io_uring, sendfile).\n")
	_, _ = sb.WriteString("- **Network activity** covers common socket syscalls but may miss non-standard paths.\n")
	_, _ = sb.WriteString("- **DNS visibility** is limited to userspace UDP queries to port 53. DoT/DoH traffic is not captured.\n")
	_, _ = sb.WriteString("- **Static binaries** may not trigger expected library-level hooks.\n")
	_, _ = sb.WriteString("- **Container metadata** (container ID) is best-effort from cgroup path parsing.\n")
	_, _ = sb.WriteString("- **Event drops** may occur under high event rates (ring buffer overflow).\n")
	_, _ = sb.WriteString("- This tool does **not** claim to capture all process activity.\n")
	_, _ = sb.WriteString("\n")
}

func (s *SummaryWriter) writeFooter(sb *strings.Builder) {
	_, _ = sb.WriteString("---\n\n")
	_, _ = sb.WriteString(fmt.Sprintf("*Generated by %s at %s*\n", version.Full(), s.endTime.Format(time.RFC3339)))
}
